Under-The-C/Backend

build.gradle, src/main/java/LikeLion/UnderTheCBackend/UnderTheCBackendApplication.java, src/main/java/LikeLion/UnderTheCBackend/config/ApiDocumentationConfig.java, src/main/java/LikeLion/UnderTheCBackend/config/SecurityConfig.java, src/main/java/LikeLion/UnderTheCBackend/controller/IndexController.java
=> Feat: Swagger 추가

src/main/java/LikeLion/UnderTheCBackend/Entity/Product.java, src/main/java/LikeLion/UnderTheCBackend/repository/ProductRepository.java
-Product repository추가
-Product Entity 추가 (외래키 설정, main_image 수정  필요)
=> Docs: Product repository 추가

src/main/java/LikeLion/UnderTheCBackend/controller/SaleProductController.java, src/main/java/LikeLion/UnderTheCBackend/controller/SearchProductController.java, src/main/java/LikeLion/UnderTheCBackend/repository/ProductRepository.java
-판매 상품 API 추가
-상품 검색 API 추가(리뷰순, 조회순, 키워드 검색 미구현)
=> Feat: 판매 상품 API, 상품 검색 API 추가

src/main/java/LikeLion/UnderTheCBackend/controller/SaleProductController.java, src/main/java/LikeLion/UnderTheCBackend/repository/ProductRepository.java
-SaleProductController 추가
-ProductRepository 추가
=> Feat: 상품 판매 API 추가

src/main/java/LikeLion/UnderTheCBackend/controller/SearchProductController.java, src/main/java/LikeLion/UnderTheCBackend/entity/Product.java, src/main/java/LikeLion/UnderTheCBackend/repository/ProductRepository.java
-카테고리 검색 API추가
-키워드 검색 API추가
-각 API에 조회순, 리뷰순 추가 예정
=> Feat: 검색 API 카테고리, 키워드 검색 추가

src/main/java/LikeLion/UnderTheCBackend/controller/SaleProductController.java, src/main/java/LikeLion/UnderTheCBackend/entity/Product.java
-판매상품 API 조회수 증가기능 추가
-entity - product 의 소제목, 추가 설명 추가, 년 월 일 만 표시되도록 Date 포맷 설정
=> Feat: 판매상품 조회수, 소제목, 추가설명 추가

src/main/java/LikeLion/UnderTheCBackend/controller/SaleProductController.java, src/main/java/LikeLion/UnderTheCBackend/controller/SearchProductController.java, src/main/java/LikeLion/UnderTheCBackend/repository/ProductRepository.java
=> Feat: 검색API 조회순 정렬 추가

build.gradle, src/main/java/LikeLion/UnderTheCBackend/config/WebClientConfig.java, src/main/java/LikeLion/UnderTheCBackend/controller/BuyerController.java, src/main/java/LikeLion/UnderTheCBackend/controller/LoginController.java, src/main/java/LikeLion/UnderTheCBackend/controller/OAuthController.java, src/main/java/LikeLion/UnderTheCBackend/controller/SellerController.java, src/main/java/LikeLion/UnderTheCBackend/controller/SignUpController.java, src/main/java/LikeLion/UnderTheCBackend/dto/KakaoAccount.java, src/main/java/LikeLion/UnderTheCBackend/dto/KakaoBuyerInfoResponse.java, src/main/java/LikeLion/UnderTheCBackend/dto/KakaoSellerInfoResponse.java, src/main/java/LikeLion/UnderTheCBackend/dto/KakaoTokenResponse.java, src/main/java/LikeLion/UnderTheCBackend/dto/LoginRequest.java, src/main/java/LikeLion/UnderTheCBackend/dto/LoginResponseForBuyer.java, src/main/java/LikeLion/UnderTheCBackend/dto/LoginResponseForSeller.java, src/main/java/LikeLion/UnderTheCBackend/utils/KakaoBuyerInfo.java, src/main/java/LikeLion/UnderTheCBackend/utils/KakaoSellerInfo.java, src/main/java/LikeLion/UnderTheCBackend/utils/KakaoTokenJsonData.java, src/main/resources/application.properties, src/test/resources/application.yml
=> Feat: 회원가입 api 추가

src/main/java/LikeLion/UnderTheCBackend/controller/ReviewController.java, src/main/java/LikeLion/UnderTheCBackend/controller/SaleProductController.java, src/main/java/LikeLion/UnderTheCBackend/controller/SearchProductController.java, src/main/java/LikeLion/UnderTheCBackend/entity/Product.java, src/main/java/LikeLion/UnderTheCBackend/entity/ProductDetailImage.java, src/main/java/LikeLion/UnderTheCBackend/entity/ProductKeyword.java, src/main/java/LikeLion/UnderTheCBackend/entity/Review.java, src/main/java/LikeLion/UnderTheCBackend/entity/ReviewImage.java, src/main/java/LikeLion/UnderTheCBackend/repository/ProductRepository.java, src/main/java/LikeLion/UnderTheCBackend/repository/ReviewRepository.java
-Review API 추가
-상품 생성 시 viewCount가 null값으로 초기화되는 현상 수정
-List<String>타입의 즉시 로딩을 위해 @OneToMany 매핑,  fetch = FetchType.EAGER 옵션을 사용
(즉시 로딩이 되지 않을 경우 could not initialize proxy - no Session 오류 발생)
-entity변화로 인해 검색API - keyword검색 기능의 not match parameter type 발생
(실행에는 문제 없으나 기능이 작동하지 않아 수정 예정)
-게시글 리뷰 조회, 작성한 리뷰 조회 추가 예정
=> Feat: Review API 추가

src/main/java/LikeLion/UnderTheCBackend/controller/LoginController.java, src/main/java/LikeLion/UnderTheCBackend/controller/OAuthController.java, src/main/java/LikeLion/UnderTheCBackend/controller/UserController.java, src/main/java/LikeLion/UnderTheCBackend/dto/AddUser.java, src/main/java/LikeLion/UnderTheCBackend/dto/KakaoAccount.java, src/main/java/LikeLion/UnderTheCBackend/dto/UpdateUser.java, src/main/java/LikeLion/UnderTheCBackend/entity/User.java, src/main/java/LikeLion/UnderTheCBackend/service/UserService.java
=> Feat: api 수정

src/main/java/LikeLion/UnderTheCBackend/controller/ReviewController.java, src/main/java/LikeLion/UnderTheCBackend/entity/Product.java, src/main/java/LikeLion/UnderTheCBackend/entity/Review.java, src/main/java/LikeLion/UnderTheCBackend/repository/ReviewRepository.java
-해당 상품 리뷰  조회, 작성한 리뷰 조회 API 추가
-product entity에 averageReviewPoint(리뷰 평균 별점) 추가
-**검색 기능 현재 수정중**
=> Feat: 상품 리뷰,작성한 리뷰 조회 기능 추가(검색기능 수정중)

src/main/java/LikeLion/UnderTheCBackend/controller/SearchProductController.java, src/main/java/LikeLion/UnderTheCBackend/entity/Product.java, src/main/java/LikeLion/UnderTheCBackend/entity/ProductKeyword.java, src/main/java/LikeLion/UnderTheCBackend/entity/ProductKeywordConnect.java, src/main/java/LikeLion/UnderTheCBackend/repository/ProductRepository.java
-Product의 name, ProductKeyword의 keyword를 동시 참조해 상품을 반환하는 기능 추가
-상품 검색 500에러 수정
=> Feat: 상품명, 키워드 동시검색 기능 추가

src/main/java/LikeLion/UnderTheCBackend/config/CustomFilter.java, src/main/java/LikeLion/UnderTheCBackend/config/CustomHttpServletResponseWrapper.java, src/main/java/LikeLion/UnderTheCBackend/controller/LoginController.java, src/main/java/LikeLion/UnderTheCBackend/controller/OAuthController.java, src/main/java/LikeLion/UnderTheCBackend/controller/SearchProductController.java, src/main/java/LikeLion/UnderTheCBackend/controller/UserController.java, src/main/java/LikeLion/UnderTheCBackend/dto/AddUser.java, src/main/java/LikeLion/UnderTheCBackend/dto/KakaoAccount.java, src/main/java/LikeLion/UnderTheCBackend/entity/Product.java, src/main/java/LikeLion/UnderTheCBackend/entity/ProductKeyword.java, src/main/java/LikeLion/UnderTheCBackend/entity/ProductKeywordConnect.java, src/main/java/LikeLion/UnderTheCBackend/entity/User.java, src/main/java/LikeLion/UnderTheCBackend/repository/ProductRepository.java, src/main/java/LikeLion/UnderTheCBackend/service/UserService.java, src/main/resources/application-prod.properties, src/main/resources/application.properties
=> Feat:  Oauth api 구현 + 유저  구별값 id로 통일

src/main/java/LikeLion/UnderTheCBackend/controller/UserController.java
=> Feat: user api 수정

src/main/java/LikeLion/UnderTheCBackend/controller/SearchProductController.java, src/main/java/LikeLion/UnderTheCBackend/entity/Product.java, src/main/java/LikeLion/UnderTheCBackend/repository/ProductRepository.java
-sellerId를 기준으로 product를 반환하는 기능을 searchProductController에 추가
=> Feat: 판매자의 상품검색 기능 추가

src/main/java/LikeLion/UnderTheCBackend/controller/ReviewController.java
-ReviewImage MultipartFile타입으로 받도록 수정
=> Fix: ReviewImage MultipartFile타입으로 받도록 수정

src/main/java/LikeLion/UnderTheCBackend/controller/ReviewController.java
-ReviewImage를 required하지 않도록 변경
=> Fix: ReviewImage를 required하지 않도록 변경

src/main/java/LikeLion/UnderTheCBackend/controller/ReviewController.java, src/main/java/LikeLion/UnderTheCBackend/entity/Product.java
- Product 엔티티 seller_id -> sellerId 변경
=> Fix: Product 엔티티 seller_id -> sellerId 변경

src/main/java/LikeLion/UnderTheCBackend/controller/ReviewController.java
=> Fix: 리뷰 이미지 업로드 오류 수정

src/main/java/LikeLion/UnderTheCBackend/controller/SaleProductController.java, src/main/java/LikeLion/UnderTheCBackend/entity/ProductKeyword.java, src/main/java/LikeLion/UnderTheCBackend/entity/ProductKeywordConnect.java
=> Feat: keywords 중복생성이 불가능 하도록 수정

src/main/java/LikeLion/UnderTheCBackend/controller/ReviewController.java, src/main/java/LikeLion/UnderTheCBackend/controller/SaleProductController.java, src/main/java/LikeLion/UnderTheCBackend/entity/Product.java
- 이미지 저장 경로 변경
- product의 keyword가 중복되면 거부되는 오류 수정 중
=> Fix: 이미지 저장 경로 변경

src/main/java/LikeLion/UnderTheCBackend/controller/ReviewController.java, src/main/java/LikeLion/UnderTheCBackend/controller/SaleProductController.java
=> Fix: images디렉토리가 없을경우 생성하도록 수정

src/main/java/LikeLion/UnderTheCBackend/controller/UserController.java
=> Feat: 프로필 이미지 업로드 수정

src/main/java/LikeLion/UnderTheCBackend/controller/UserController.java, src/main/java/LikeLion/UnderTheCBackend/dto/AddUser.java, src/main/java/LikeLion/UnderTheCBackend/repository/UserRepository.java
=> Feat: 유저 role 수정2

src/main/java/LikeLion/UnderTheCBackend/controller/UserController.java, src/main/java/LikeLion/UnderTheCBackend/dto/AddUser.java, src/main/java/LikeLion/UnderTheCBackend/dto/UpdateUser.java
=> Feat: 이미지 파일 업로드 수정

src/main/java/LikeLion/UnderTheCBackend/controller/SaleProductController.java, src/main/java/LikeLion/UnderTheCBackend/dto/ResponseProduct.java
-판매 상품 찾기API가 ResponseProduct객체를 반환하도록 수정
-판매 상품 모두 찾기API가 ResponseProduct객체를 반환하도록 수정
=> Fix: 판매 상품 찾기, 모두 찾기API가 ResponseProduct객체를 반환하도록 수정

src/main/java/LikeLion/UnderTheCBackend/controller/SaleProductController.java
=> Fix: 더미데이터의 category값 수정

src/main/java/LikeLion/UnderTheCBackend/controller/SaleProductController.java
- convertToResponseProduct에서 List<String>변환이 불가능한 현상 수정
=> Fix: convertToResponseProduct에서 List<String>변환이 불가능한 현상 수정
